INSERT INTO `mobile_phrases` (`name`, `value`) VALUES
('the_events', 'ÇáÇÍÏÇË'),
('the_events_types', 'ÇäæÇÚ ÇáÇÍÏÇË'),
('event_not_exists', 'ÇáÍÏË ÛíÑ ãæÌæÏ'),
('no_events', 'áÇ ÊæÌÏ ÇÍÏÇË'),
('january', 'íäÇíÑ'),
('february', 'ÝÈÑÇíÑ'),
('march', 'ãÇÑÓ'),
('april', 'ÇÈÑíá'),
('may', 'ãÇíæ'),
('june', 'íæäíæ'),
('july', 'íæáíæ'),
('august', 'ÇÛÓØÓ'),
('september', 'ÓÈÊãÈÑ'),
('october', 'ÇßÊæÈÑ'),
('november', 'äæÝãÈÑ'),
('december', 'ÏíÓãÈÑ'),
('events_prev', 'ÇáÍÏË ÇáÓÇÈÞ'),
('events_next', 'ÇáÍÏË ÇáÊÇáí'),
('add_event', 'ÇÖÇÝÉ ÍÏË'),
('events_no_types', 'áÇ ÊæÌÏ ÇäæÇÚ'),
('events_add', 'ÇÖÇÝÉ ÍÏË'),
('the_color', 'Çááæä');